const fs = require('fs');
const T = String.fromCharCode(96);
const q = String.fromCharCode(34);
const L = (s) => lines.push(s);
const lines = [];

L("'use client';");
L("");
L("import { useEffect, useState } from 'react';");
L("import { motion } from 'framer-motion';");
L("import { FloatingMoney } from '@/components/animations/FloatingMoney';");
L("import { MoneyFlowCanvas } from '@/components/animations/MoneyFlowCanvas';");
L("import { NeuralNetwork } from '@/components/animations/NeuralNetwork';");
L("import { UrgencyPulse } from '@/components/ui/UrgencyPulse';");
L("import { PulseGlow } from '@/components/animations/PulseGlow';");
L("import { containerVariants, itemVariants } from '@/lib/animations';");
L("import { formatCurrency } from '@/lib/revenue-tracker';");
L("import { Zap, TrendingUp, DollarSign, Flame, ExternalLink, Mail, Users, RefreshCw, Play, Square } from 'lucide-react';");
L("import Link from 'next/link';");
L("");
L("interface EngineData {");
L("  status: { isRunning: boolean; lastHunt: string | null; totalCycles: number; uptime: string; errors: string[] };");
L("  prospects: { total: number; found: number; contacted: number; replied: number; closed: number;");
L("    topProspects: Array<{ name: string; industry: string; painPoints: string[]; score: number; estimatedValue: number; source: string }> };");
L("  outreach: { totalSent: number; emailsSent: number; queued: number;");
L("    recentEmails: Array<{ to: string; subject: string; service: string; status: string; sentAt: string }> };");
L("  deliveries: { totalDeliveries: number; totalRevenue: number; pending: number; inProgress: number; delivered: number };");
L("}");
L("");
L("export default function HomePage() {");
L("  const [data, setData] = useState<EngineData | null>(null);");
L("  const [loading, setLoading] = useState(true);");
L("  const [actionLoading, setActionLoading] = useState<string | null>(null);");
L("");
L("  const fetchStatus = async () => {");
L("    try { const r = await fetch('/api/engine'); const j = await r.json(); setData(j); setLoading(false); }");
L("    catch { setLoading(false); }");
L("  };");
L("  const triggerCycle = async () => { setActionLoading('cycle'); try { await fetch('/api/engine', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: '{}' }); await fetchStatus(); } catch {} setActionLoading(null); };");
L("  const startEngine = async () => { setActionLoading('start'); await fetch('/api/engine', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'start', intervalMs: 300000 }) }); await fetchStatus(); setActionLoading(null); };");
L("  const stopEngine = async () => { setActionLoading('stop'); await fetch('/api/engine', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'stop' }) }); await fetchStatus(); setActionLoading(null); };");
L("");
L("  useEffect(() => { fetchStatus(); const i = setInterval(fetchStatus, 8000); return () => clearInterval(i); }, []);");
L("");
L("  if (loading) return (<div className='min-h-screen flex items-center justify-center' style={{ background: '#0a0e27' }}><motion.div animate={{ rotate: 360 }} transition={{ duration: 1.5, repeat: Infinity, ease: 'linear' }}><Zap className='w-12 h-12 text-neon-green' /></motion.div></div>);");
L("");
L("  const pipeline = (data?.prospects.topProspects || []).reduce((s, p) => s + p.estimatedValue, 0);");
L("");
L("  return (<>");
L("    <MoneyFlowCanvas /><NeuralNetwork />");
L("    <motion.main variants={containerVariants} initial='hidden' animate='visible' className='relative min-h-screen p-4 lg:p-6 xl:p-8' style={{ zIndex: 2 }}>");
L("      <motion.header variants={itemVariants} className='mb-6 lg:mb-8'>");
L("        <div className='flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 mb-5'>");
L("          <div>");
L("            <div className='flex items-center gap-3 mb-1'>");
L("              <motion.h1 className='text-3xl lg:text-5xl font-black text-neon-green tracking-tight' style={{ textShadow: '0 0 20px rgba(0,255,65,0.4)' }} animate={{ textShadow: ['0 0 20px rgba(0,255,65,0.4)', '0 0 30px rgba(0,255,65,0.6)', '0 0 20px rgba(0,255,65,0.4)'] }} transition={{ duration: 3, repeat: Infinity }}>WEALTH MACHINE</motion.h1>");
L("              <motion.div animate={{ rotate: 360 }} transition={{ duration: 4, repeat: Infinity, ease: 'linear' }}><Flame className='w-6 h-6 lg:w-8 lg:h-8 text-neon-red' /></motion.div>");
L("            </div>");
L("            <p className='text-neon-blue/80 text-[10px] lg:text-xs uppercase tracking-[0.3em]'>Real Revenue Engine</p>");
L("          </div>");
L("          <div className='flex items-center gap-3'>");
L("            <Link href='/ops' className='px-3 py-1.5 rounded-lg bg-neon-blue/10 border border-neon-blue/30 text-neon-blue text-xs font-bold hover:bg-neon-blue/20 transition flex items-center gap-1.5'><Zap className='w-3 h-3' /> ENGINE <ExternalLink className='w-2.5 h-2.5' /></Link>");
L("            <Link href='/sell' className='px-3 py-1.5 rounded-lg bg-neon-purple/10 border border-neon-purple/30 text-neon-purple text-xs font-bold hover:bg-neon-purple/20 transition flex items-center gap-1.5'>SELL <ExternalLink className='w-2.5 h-2.5' /></Link>");
L("          </div>");
L("        </div>");
L("        <div className='flex gap-2 mb-4 flex-wrap'>");
L("          <button onClick={triggerCycle} disabled={actionLoading === 'cycle'} className='flex items-center gap-1.5 px-3 py-2 rounded-lg bg-neon-green text-dark-bg font-black text-xs hover:opacity-90 transition disabled:opacity-50'><RefreshCw className={'w-3 h-3 ' + (actionLoading === 'cycle' ? 'animate-spin' : '')} /> HUNT NOW</button>");
L("          {!data?.status.isRunning ? (<button onClick={startEngine} className='flex items-center gap-1.5 px-3 py-2 rounded-lg bg-neon-blue/10 text-neon-blue border border-neon-blue/30 font-bold text-xs hover:bg-neon-blue/20 transition'><Play className='w-3 h-3' /> AUTO</button>)");
L("           : (<button onClick={stopEngine} className='flex items-center gap-1.5 px-3 py-2 rounded-lg bg-neon-red/10 text-neon-red border border-neon-red/30 font-bold text-xs hover:bg-neon-red/20 transition'><Square className='w-3 h-3' /> STOP</button>)}");
L("          <div className={'flex items-center gap-1.5 px-3 py-2 rounded-lg text-xs font-bold ' + (data?.status.isRunning ? 'bg-neon-green/10 text-neon-green border border-neon-green/30' : 'bg-dark-card text-os-dim border border-os-dim/30')}>");
L("            <div className={'w-2 h-2 rounded-full ' + (data?.status.isRunning ? 'bg-neon-green animate-pulse' : 'bg-os-dim')} />");
L("            {data?.status.isRunning ? 'RUNNING' : 'STOPPED'} - {data?.status.totalCycles || 0} cycles");
L("          </div>");
L("        </div>");
L("        <div className='grid grid-cols-1 md:grid-cols-3 gap-2'>");
L("          <UrgencyPulse message={(data?.prospects.total || 0) + ' real prospects found'} severity='high' />");
L("          <UrgencyPulse message={(data?.outreach.emailsSent || 0) + ' emails sent / ' + (data?.outreach.queued || 0) + ' queued'} severity='medium' />");
L("          <UrgencyPulse message={'$' + pipeline.toLocaleString() + ' pipeline value'} severity='low' />");
L("        </div>");
L("      </motion.header>");
L("");
L("      <motion.div variants={itemVariants} className='grid grid-cols-2 lg:grid-cols-4 gap-3 mb-6'>");
L("        {[{ l: 'Real Prospects', v: String(data?.prospects.total || 0), c: 'text-neon-green', i: <Users className='w-4 h-4' /> },");
L("          { l: 'Emails Sent', v: String(data?.outreach.emailsSent || 0), c: 'text-neon-blue', i: <Mail className='w-4 h-4' /> },");
L("          { l: 'Pipeline', v: '$' + pipeline.toLocaleString(), c: 'text-neon-purple', i: <DollarSign className='w-4 h-4' /> },");
L("          { l: 'Closed', v: '$' + (data?.deliveries.totalRevenue || 0).toLocaleString(), c: 'text-neon-red', i: <TrendingUp className='w-4 h-4' /> }");
L("        ].map(m => (<div key={m.l} className='glass-card p-4 rounded-xl border border-white/5'><div className='flex items-center just
