L("");
L("      <motion.div variants={itemVariants} className='grid grid-cols-2 lg:grid-cols-4 gap-3 mb-6'>");
L("        {[{ l: 'Real Prospects', v: String(data?.prospects.total || 0), c: 'text-neon-green', i: <Users className='w-4 h-4' /> },");
L("          { l: 'Emails Sent', v: String(data?.outreach.emailsSent || 0), c: 'text-neon-blue', i: <Mail className='w-4 h-4' /> },");
L("          { l: 'Pipeline', v: '$' + pipeline.toLocaleString(), c: 'text-neon-purple', i: <DollarSign className='w-4 h-4' /> },");
L("          { l: 'Closed', v: '$' + (data?.deliveries.totalRevenue || 0).toLocaleString(), c: 'text-neon-red', i: <TrendingUp className='w-4 h-4' /> }");
L("        ].map(m => (<div key={m.l} className='glass-card p-4 rounded-xl border border-white/5'><div className='flex items-center justify-between mb-1'><p className='text-[9px] uppercase tracking-widest text-os-dim'>{m.l}</p><span className={m.c}>{m.i}</span></div><p className={'text-2xl font-black ' + m.c}>{m.v}</p></div>))}");
L("      </motion.div>");
L("");
L("      <motion.div variants={itemVariants} className='grid grid-cols-1 lg:grid-cols-2 gap-5 mb-6'>");
L("        <div className='glass-card p-5 rounded-xl border border-neon-green/10'>");
L("          <h2 className='text-sm font-bold text-neon-green mb-4'>REAL PROSPECTS</h2>");
L("          <div className='space-y-2 max-h-80 overflow-y-auto'>");
L("            {(data?.prospects.topProspects || []).map((p, i) => (");
L("              <div key={p.name + i} className='p-3 rounded-lg border border-white/5 bg-white/[0.02] hover:border-neon-green/20 transition'>");
L("                <div className='flex items-center justify-between mb-1'><span className='text-xs font-bold'>{p.name}</span><span className='text-[10px] px-2 py-0.5 rounded-full bg-neon-green/10 text-neon-green'>Score: {p.score}</span></div>");
L("                <div className='flex items-center justify-between'><span className='text-[10px] text-os-dim'>{p.industry} / {p.source}</span><span className='text-[10px] font-bold text-neon-blue'>$' + '{p.estimatedValue.toLocaleString()}' + '</span></div>");
L("                {p.painPoints.length > 0 && <div className='flex gap-1 mt-1.5 flex-wrap'>{p.painPoints.slice(0, 3).map(pp => <span key={pp} className='text-[8px] px-1.5 py-0.5 rounded bg-neon-purple/10 text-neon-purple'>{pp}</span>)}</div>}");
L("              </div>))}");
L("            {(!data?.prospects.topProspects || data.prospects.topProspects.length === 0) && <p className='text-xs text-os-dim text-center py-8'>No prospects yet. Click HUNT NOW.</p>}");
L("          </div>");
L("        </div>");
L("        <div className='glass-card p-5 rounded-xl border border-neon-blue/10'>");
L("          <h2 className='text-sm font-bold text-neon-blue mb-4'>RECENT OUTREACH</h2>");
L("          <div className='space-y-2 max-h-80 overflow-y-auto'>");
L("            {(data?.outreach.recentEmails || []).map((e, i) => (");
L("              <div key={i} className='p-3 rounded-lg border border-white/5 bg-white/[0.02]'>");
L("                <div className='flex items-center justify-between mb-1'><span className='text-xs font-bold'>{e.to}</span><span className={'text-[10px] px-2 py-0.5 rounded-full ' + (e.status === 'sent' ? 'bg-neon-green/10 text-neon-green' : 'bg-yellow-500/10 text-yellow-400')}>{e.status}</span></div>");
L("                <p className='text-[10px] text-os-dim truncate'>{e.subject}</p>");
L("                <p className='text-[9px] text-os-dim/50 mt-0.5'>{e.service}</p>");
L("              </div>))}");
L("            {(!data?.outreach.recentEmails || data.outreach.recentEmails.length === 0) && <p className='text-xs text-os-dim text-center py-8'>No outreach yet.</p>}");
L("          </div>");
L("        </div>");
L("      </motion.div>");
