L("");
L("      <motion.div variants={itemVariants} className='glass-card p-5 rounded-xl border border-neon-green/10'>");
L("        <h2 className='text-sm font-bold text-neon-green mb-3'>ACTIVATE FULL AUTONOMY</h2>");
L("        <div className='grid grid-cols-1 md:grid-cols-2 gap-4 text-xs text-os-dim'>");
L("          <div className='space-y-2'><p><code className='text-neon-blue'>RESEND_API_KEY</code> - emails actually get sent</p><p><code className='text-neon-blue'>STRIPE_SECRET_KEY</code> - payments actually process</p><p><code className='text-neon-blue'>GOOGLE_API_KEY</code> - prospects found via Google</p></div>");
L("          <div className='space-y-2'><p>Click HUNT NOW - engine finds real people</p><p>Click AUTO - engine runs every 5 min</p><p>Add API keys - emails send, payments process, revenue flows</p></div>");
L("        </div>");
L("      </motion.div>");
L("");
L("      <motion.footer variants={itemVariants} className='mt-6 glass-card p-4 rounded-xl border border-neon-green/10 text-center'>");
L("        <div className='flex items-center justify-center gap-2 mb-2'><PulseGlow color='green' size='sm' /><p className='text-xs font-bold text-neon-green uppercase tracking-widest'>{data?.status.isRunning ? 'ENGINE RUNNING' : 'ENGINE READY'}</p><PulseGlow color='green' size='sm' /></div>");
L("        <p className='text-[9px] text-os-dim'>{data?.prospects.total || 0} prospects - {data?.outreach.emailsSent || 0} emails - {data?.status.totalCycles || 0} cycles - {data?.status.uptime || '0h 0m'} uptime</p>");
L("      </motion.footer>");
L("    </motion.main>");
L("    <FloatingMoney />");
L("  </>);");
L("}");
