import type { Agent, AgentMetrics, Deal } from '@/types';

const AGENT_CONFIGS: Record<string, Partial<Agent>> = {
  closer: {
    name: '💰 Deal Closer',
    type: 'closer',
    dailyTarget: 15000,
  },
  'offer-engineer': {
    name: '🔧 Offer Engineer',
    type: 'offer-engineer',
    dailyTarget: 5000,
  },
  'traffic-gunner': {
    name: '🎯 Traffic Gunner',
    type: 'traffic-gunner',
    dailyTarget: 8000,
  },
  'partner-predator': {
    name: '🦁 Partnership Predator',
    type: 'partner-predator',
    dailyTarget: 12000,
  },
  'product-machine': {
    name: '⚙️ Product Machine',
    type: 'product-machine',
    dailyTarget: 6000,
  },
  'community-operator': {
    name: '👥 Community Operator',
    type: 'community-operator',
    dailyTarget: 9000,
  },
  'money-optimizer': {
    name: '💵 Money Optimizer',
    type: 'money-optimizer',
    dailyTarget: 3000,
  },
  'growth-hacker': {
    name: '🚀 Growth Hacker',
    type: 'growth-hacker',
    dailyTarget: 7000,
  },
};

export function generateAgents(): Agent[] {
  return [
    {
      id: 'agent-1',
      name: AGENT_CONFIGS.closer?.name || 'Closer',
      type: 'closer',
      status: 'hunting',
      autonomyLevel: 85,
      dailyTarget: 15000,
      dailyActual: Math.floor(Math.random() * 15000),
      conversionRate: 45 + Math.random() * 20,
      lastActive: new Date().toISOString(),
      dealsThisHour: Math.floor(Math.random() * 5),
      totalRevenue: 150000 + Math.random() * 50000,
      efficiency: 78 + Math.random() * 22,
      aggressiveness: 95,
    },
    {
      id: 'agent-2',
      name: AGENT_CONFIGS['offer-engineer']?.name || 'Offer Engineer',
      type: 'offer-engineer',
      status: 'active',
      autonomyLevel: 72,
      dailyTarget: 5000,
      dailyActual: Math.floor(Math.random() * 5000),
      conversionRate: 38 + Math.random() * 15,
      lastActive: new Date().toISOString(),
      dealsThisHour: Math.floor(Math.random() * 3),
      totalRevenue: 85000 + Math.random() * 30000,
      efficiency: 82 + Math.random() * 18,
      aggressiveness: 80,
    },
    {
      id: 'agent-3',
      name: AGENT_CONFIGS['traffic-gunner']?.name || 'Traffic Gunner',
      type: 'traffic-gunner',
      status: 'hunting',
      autonomyLevel: 88,
      dailyTarget: 8000,
      dailyActual: Math.floor(Math.random() * 8000),
      conversionRate: 32 + Math.random() * 18,
      lastActive: new Date().toISOString(),
      dealsThisHour: Math.floor(Math.random() * 4),
      totalRevenue: 120000 + Math.random() * 40000,
      efficiency: 75 + Math.random() * 25,
      aggressiveness: 92,
    },
    {
      id: 'agent-4',
      name: AGENT_CONFIGS['partner-predator']?.name || 'Partnership Predator',
      type: 'partner-predator',
      status: 'hunting',
      autonomyLevel: 90,
      dailyTarget: 12000,
      dailyActual: Math.floor(Math.random() * 12000),
      conversionRate: 28 + Math.random() * 20,
      lastActive: new Date().toISOString(),
      dealsThisHour: Math.floor(Math.random() * 6),
      totalRevenue: 180000 + Math.random() * 60000,
      efficiency: 81 + Math.random() * 19,
      aggressiveness: 98,
    },
    {
      id: 'agent-5',
      name: AGENT_CONFIGS['product-machine']?.name || 'Product Machine',
      type: 'product-machine',
      status: 'active',
      autonomyLevel: 65,
      dailyTarget: 6000,
      dailyActual: Math.floor(Math.random() * 6000),
      conversionRate: 42 + Math.random() * 16,
      lastActive: new Date().toISOString(),
      dealsThisHour: Math.floor(Math.random() * 3),
      totalRevenue: 95000 + Math.random() * 35000,
      efficiency: 79 + Math.random() * 21,
      aggressiveness: 75,
    },
    {
      id: 'agent-6',
      name: AGENT_CONFIGS['community-operator']?.name || 'Community Operator',
      type: 'community-operator',
      status: 'active',
      autonomyLevel: 70,
      dailyTarget: 9000,
      dailyActual: Math.floor(Math.random() * 9000),
      conversionRate: 35 + Math.random() * 17,
      lastActive: new Date().toISOString(),
      dealsThisHour: Math.floor(Math.random() * 2),
      totalRevenue: 110000 + Math.random() * 38000,
      efficiency: 83 + Math.random() * 17,
      aggressiveness: 70,
    },
    {
      id: 'agent-7',
      name: AGENT_CONFIGS['money-optimizer']?.name || 'Money Optimizer',
      type: 'money-optimizer',
      status: 'active',
      autonomyLevel: 88,
      dailyTarget: 3000,
      dailyActual: Math.floor(Math.random() * 3000),
      conversionRate: 55 + Math.random() * 25,
      lastActive: new Date().toISOString(),
      dealsThisHour: Math.floor(Math.random() * 2),
      totalRevenue: 60000 + Math.random() * 20000,
      efficiency: 92 + Math.random() * 8,
      aggressiveness: 65,
    },
    {
      id: 'agent-8',
      name: AGENT_CONFIGS['growth-hacker']?.name || 'Growth Hacker',
      type: 'growth-hacker',
      status: 'hunting',
      autonomyLevel: 85,
      dailyTarget: 7000,
      dailyActual: Math.floor(Math.random() * 7000),
      conversionRate: 38 + Math.random() * 16,
      lastActive: new Date().toISOString(),
      dealsThisHour: Math.floor(Math.random() * 4),
      totalRevenue: 100000 + Math.random() * 35000,
      efficiency: 80 + Math.random() * 20,
      aggressiveness: 88,
    },
  ];
}

export function simulateAgentActivity(agent: Agent): Partial<Agent> {
  const statusPool: Agent['status'][] = ['active', 'hunting', 'closing', 'idle'];
  const newStatus = statusPool[Math.floor(Math.random() * statusPool.length)];
  
  return {
    status: newStatus,
    dailyActual: Math.min(agent.dailyTarget, agent.dailyActual + Math.floor(Math.random() * 1000)),
    dealsThisHour: Math.floor(Math.random() * 8),
    totalRevenue: agent.totalRevenue + Math.floor(Math.random() * 5000),
    conversionRate: Math.min(100, agent.conversionRate + (Math.random() - 0.5) * 5),
    efficiency: Math.max(0, Math.min(100, agent.efficiency + (Math.random() - 0.5) * 3)),
    lastActive: new Date().toISOString(),
  };
}
