import type { Agent } from '@/types';

export function generateAgents(): Agent[] {
  const now = new Date().toISOString();

  return [
    {
      id: 'agent-1',
      name: '💰 Deal Closer',
      type: 'closer',
      status: 'hunting',
      autonomyLevel: 85,
      dailyTarget: 15000,
      dailyActual: Math.floor(8000 + Math.random() * 7000),
      conversionRate: 45 + Math.random() * 20,
      lastActive: now,
      dealsThisHour: Math.floor(1 + Math.random() * 4),
      totalRevenue: 150000 + Math.random() * 50000,
      efficiency: 78 + Math.random() * 22,
      aggressiveness: 95,
    },
    {
      id: 'agent-2',
      name: '🔧 Offer Engineer',
      type: 'offer-engineer',
      status: 'active',
      autonomyLevel: 72,
      dailyTarget: 5000,
      dailyActual: Math.floor(2000 + Math.random() * 3000),
      conversionRate: 38 + Math.random() * 15,
      lastActive: now,
      dealsThisHour: Math.floor(Math.random() * 3),
      totalRevenue: 85000 + Math.random() * 30000,
      efficiency: 82 + Math.random() * 18,
      aggressiveness: 80,
    },
    {
      id: 'agent-3',
      name: '🎯 Traffic Gunner',
      type: 'traffic-gunner',
      status: 'hunting',
      autonomyLevel: 88,
      dailyTarget: 8000,
      dailyActual: Math.floor(3000 + Math.random() * 5000),
      conversionRate: 32 + Math.random() * 18,
      lastActive: now,
      dealsThisHour: Math.floor(1 + Math.random() * 3),
      totalRevenue: 120000 + Math.random() * 40000,
      efficiency: 75 + Math.random() * 25,
      aggressiveness: 92,
    },
    {
      id: 'agent-4',
      name: '🦁 Partnership Predator',
      type: 'partner-predator',
      status: 'hunting',
      autonomyLevel: 90,
      dailyTarget: 12000,
      dailyActual: Math.floor(5000 + Math.random() * 7000),
      conversionRate: 28 + Math.random() * 20,
      lastActive: now,
      dealsThisHour: Math.floor(2 + Math.random() * 4),
      totalRevenue: 180000 + Math.random() * 60000,
      efficiency: 81 + Math.random() * 19,
      aggressiveness: 98,
    },
    {
      id: 'agent-5',
      name: '⚙️ Product Machine',
      type: 'product-machine',
      status: 'active',
      autonomyLevel: 65,
      dailyTarget: 6000,
      dailyActual: Math.floor(2500 + Math.random() * 3500),
      conversionRate: 42 + Math.random() * 16,
      lastActive: now,
      dealsThisHour: Math.floor(Math.random() * 3),
      totalRevenue: 95000 + Math.random() * 35000,
      efficiency: 79 + Math.random() * 21,
      aggressiveness: 75,
    },
    {
      id: 'agent-6',
      name: '👥 Community Operator',
      type: 'community-operator',
      status: 'active',
      autonomyLevel: 70,
      dailyTarget: 9000,
      dailyActual: Math.floor(4000 + Math.random() * 5000),
      conversionRate: 35 + Math.random() * 17,
      lastActive: now,
      dealsThisHour: Math.floor(Math.random() * 2),
      totalRevenue: 110000 + Math.random() * 38000,
      efficiency: 83 + Math.random() * 17,
      aggressiveness: 70,
    },
    {
      id: 'agent-7',
      name: '💵 Money Optimizer',
      type: 'money-optimizer',
      status: 'active',
      autonomyLevel: 88,
      dailyTarget: 3000,
      dailyActual: Math.floor(1500 + Math.random() * 1500),
      conversionRate: 55 + Math.random() * 25,
      lastActive: now,
      dealsThisHour: Math.floor(Math.random() * 2),
      totalRevenue: 60000 + Math.random() * 20000,
      efficiency: 92 + Math.random() * 8,
      aggressiveness: 65,
    },
    {
      id: 'agent-8',
      name: '🚀 Growth Hacker',
      type: 'growth-hacker',
      status: 'hunting',
      autonomyLevel: 85,
      dailyTarget: 7000,
      dailyActual: Math.floor(3000 + Math.random() * 4000),
      conversionRate: 38 + Math.random() * 16,
      lastActive: now,
      dealsThisHour: Math.floor(1 + Math.random() * 3),
      totalRevenue: 100000 + Math.random() * 35000,
      efficiency: 80 + Math.random() * 20,
      aggressiveness: 88,
    },
  ];
}

export function simulateAgentActivity(agent: Agent): Partial<Agent> {
  const statusPool: Agent['status'][] = ['active', 'hunting', 'closing', 'hunting', 'active'];
  const newStatus = statusPool[Math.floor(Math.random() * statusPool.length)];

  const revenueIncrease = Math.floor(Math.random() * 2000);

  return {
    status: newStatus,
    dailyActual: Math.min(agent.dailyTarget, agent.dailyActual + revenueIncrease),
    dealsThisHour: Math.floor(1 + Math.random() * 6),
    totalRevenue: agent.totalRevenue + revenueIncrease,
    conversionRate: Math.max(10, Math.min(100, agent.conversionRate + (Math.random() - 0.45) * 3)),
    efficiency: Math.max(20, Math.min(100, agent.efficiency + (Math.random() - 0.45) * 2)),
    lastActive: new Date().toISOString(),
  };
}
